name: 刷课
 
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs: 
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v4
 
      - name: 设置python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
 
      - name: 安装依赖包
        run: |
          pip install -r ./requirements.txt 
          
      - name: Run main.py 第1次
        env:
          CHAOXING_USERNAME: ${{ 13950530098 }}
          CHAOXING_PASSWORD: ${{ 'zp13950530098' }}
          CHAOXING_COURSE_LIST: ${{ 263232331 }}
        run: python main.py -u "$CHAOXING_USERNAME" -p "$CHAOXING_PASSWORD" -l "$CHAOXING_COURSE_LIST"

      - name: Run main.py 第2次
        env:
          CHAOXING_USERNAME: ${{ 13950530098 }}
          CHAOXING_PASSWORD: ${{ 'zp13950530098' }}
          CHAOXING_COURSE_LIST: ${{ 263232332 }}
        run: python main.py -u "$CHAOXING_USERNAME" -p "$CHAOXING_PASSWORD" -l "$CHAOXING_COURSE_LIST"
